---
abstract: 'Helper Class to generate L<Catalyst>'
author:
  - 'Benjamin Tietz <btietz@cpan.com>'
build_requires:
  DBI: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Helper-Model-UserConfig
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Catalyst::Helper: 0
  User::Config: 0.02
  User::Config::UI::HTMLFormHandler: 0
version: 0.01_00
